apiVersion: v1
kind: ResourceController
metadata:
  name: my-resource-pod
spec:
  template:
    selector:
      matchLabels:
        app: my-app
    replicas: 5
    spec:
      metadata:
        name: my-resource-app
        labels:
          app: my-app
      spec:
        containers:
          - name: my-resource-cont
            image: nginx
            port:
            - containerPort: 80
    